version: '3.8'

services:
  shorty_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shorty_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - APP_ENV=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Mohammad1367
      - DB_NAME=shorty
    networks:
      - webapi_network

  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mohammad1367
      POSTGRES_DB: shorty
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webapi_network

volumes:
  pgdata:

networks:
  webapi_network:
    driver: bridge
