server:
  port: 8001
  runMode: debug
logger:
  filePath: storage/logs/
  encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: postgres_container
  port: 5432
  username: postgres
  password: Mohammad1367
  database: shorty
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5
redis:
  host: redis_container
  port: 6379
  password: Mohammad1367
  database: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500
rateLimit:
  requestsPerSecond: 5
  burstSize: 2
